/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_channy_jnitest_MainActivity */

#ifndef _Included_com_example_channy_jnitest_MainActivity
#define _Included_com_example_channy_jnitest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_channy_jnitest_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_channy_jnitest_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_channy_jnitest_MainActivity
 * Method:    integerFromJNI
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_channy_jnitest_MainActivity_integerFromJNI
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
